// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void showkey_Animation(lv_obj_t *TargetObject, int delay);
void hidkey_Animation(lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Logo
void ui_Logo_screen_init(void);
lv_obj_t *ui_Logo;
void ui_event_gif(lv_event_t *e);
lv_obj_t *ui_gif;
lv_obj_t *ui_gifdata;

// SCREEN: ui_CLOCK
void ui_CLOCK_screen_init(void);
void ui_event_CLOCK(lv_event_t *e);
lv_obj_t *ui_CLOCK;
lv_obj_t *ui_data;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;

// SCREEN: ui_Touch_to_start
void ui_Touch_to_start_screen_init(void);
void ui_event_PasswordKey2(lv_event_t *e);
lv_obj_t *ui_Touch_to_start;
lv_obj_t *ui_Panel4;
void ui_event_ButStartstart(lv_event_t *e);
lv_obj_t *ui_ButStartstart;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label4;
void ui_event_ButStartqr(lv_event_t *e);
lv_obj_t *ui_ButStartqr;
lv_obj_t *ui_Label3;
lv_obj_t *ui_LabMsgqr;
lv_obj_t *ui_labMsgWIfiMode;
lv_obj_t *ui_labWifiMode;
lv_obj_t *ui_labMsgWIfIP;
lv_obj_t *ui_labWifiip;
lv_obj_t *ui_labMsgWIfiID;
lv_obj_t *ui_labWIfiid;
lv_obj_t *ui_labMsgWIfiPD;
lv_obj_t *ui_labWifipd;
void ui_event_connection_wifi(lv_event_t *e);
lv_obj_t *ui_connection_wifi;
lv_obj_t *ui_Label15;
lv_obj_t *ui_ConnWifi2;
lv_obj_t *ui_Label16;
lv_obj_t *ui_WifiList2;
lv_obj_t *ui_PasswordKey2;
void ui_event_Password2(lv_event_t *e);
lv_obj_t *ui_Password2;
void ui_event_BtnConnWIfi2(lv_event_t *e);
lv_obj_t *ui_BtnConnWIfi2;
lv_obj_t *ui_Label13;
lv_obj_t *ui_WIFI_Name2;
void ui_event_AreaWifiName2(lv_event_t *e);
lv_obj_t *ui_AreaWifiName2;
lv_obj_t *ui_Label14;
void ui_event_Keyboard3(lv_event_t *e);
lv_obj_t *ui_Keyboard3;
void ui_event_butskip2(lv_event_t *e);
lv_obj_t *ui_butskip2;
lv_obj_t *ui_labskip2;

// SCREEN: ui_Insert_pod
void ui_Insert_pod_screen_init(void);
void ui_event_Insert_pod(lv_event_t *e);
lv_obj_t *ui_Insert_pod;
lv_obj_t *ui_Image8;
lv_obj_t *ui_LabMsgInsert;

// SCREEN: ui_Reinforce
void ui_Reinforce_screen_init(void);
lv_obj_t *ui_Reinforce;

// SCREEN: ui_chose_coffee
void ui_chose_coffee_screen_init(void);
lv_obj_t *ui_chose_coffee;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Image6;
void ui_event_Button3(lv_event_t *e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_LabMsgIce;
void ui_event_Button1(lv_event_t *e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_LabMsghot;

// SCREEN: ui_brewing
void ui_brewing_screen_init(void);
lv_obj_t *ui_brewing;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Panel3;
void ui_event_Arc1(lv_event_t *e);
lv_obj_t *ui_Arc1;
lv_obj_t *ui_Image2;

// SCREEN: ui_Done
void ui_Done_screen_init(void);
void ui_event_Done(lv_event_t *e);
lv_obj_t *ui_Done;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label5;

// SCREEN:
void ui_Error_screen_init(void);
void ui_event_Error(lv_event_t *e);
lv_obj_t *ui_Error;
lv_obj_t *ui_ErrorMsgError;
lv_obj_t *ui_MsgErrorInfo;
lv_obj_t *ui_ImgErrormsg;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_7aaebc9043b138a2613feee3cb95b[1] = {&ui_img_7aaebc9043b138a2613feee3cb95b55_png};
// 定义任务句柄
static TaskHandle_t arcTaskHandle = NULL;
static TimerHandle_t arcTimer;
// 定义枚举类型表示不同的界面
typedef enum
{
    UI_LOGO,
    UI_CLOCK,
    UI_TOUCH_TO_START,
    UI_INSERT_POD,
    UI_REINFORCE,
    UI_CHOSE_COFFEE,
    UI_BREWING,
    UI_DONE,
    UI_ERROR
} UIType;
// 定义记录当前界面的结构体
typedef struct
{
    UIType currentUI;
    lv_obj_t *ui_Time; // 添加一个指向 UI_TIME 的指针
    uint32_t seconds;  // 记录经过的秒数
    // 可以添加其他与界面相关的信息
} UIRecord;
// 定义全局变量用于存储界面信息
UIRecord gUIRecord = {UI_LOGO, NULL, 0};
SemaphoreHandle_t gUIRecordMutex; // 用于保护 gUIRecord 的互斥信号量
uint32_t chaneScreenTime = 30;
uint8_t uiChangeTime = 50;
bool is_CloseDoor = false;
bool is_makeCoffee = false;
uint8_t MakeCoffeeTime = 5; // 制作咖啡时间
// 声明任务处理函数8`66
void uiTask(void *pvParameters);
// 声明定时器回调函数
void timerCallback(TimerHandle_t xTimer);

// 创建定时器句柄
TimerHandle_t gLogoTimer;
TimerHandle_t gClockTimer;
int ClockTime = 0;
int update_Time = 0;
bool is_WaittoLogo = false;
/// ABIMATIONS
void showkey_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 350, 105);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
}
void hidkey_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 105, 350);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
}

///////////////////// ANIMATIONS ////////////////////
// 定时器
static int progress = 0;
bool sccor = false;
int linee = 0;
void timer_callback1(void *arg)
{
    if (gUIRecord.currentUI != UI_BREWING)
        return;
    ESP_LOGI("MAKE COffee", " progress: %d is_makCOffee=%d", progress, is_makeCoffee);
    if (!is_makeCoffee)
    {
        is_makeCoffee = false;
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_ERROR;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_Error, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Error_screen_init);
        return;
    }
    if (progress < 100 && is_makeCoffee)
    {
        // 更新ARC进度条的值
        lv_arc_set_value(ui_Arc1, progress);
    }
    else
    {
        if (progress == 160)
        {
            lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            is_makeCoffee = false;
            xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
            gUIRecord.currentUI = UI_DONE;
            xSemaphoreGive(gUIRecordMutex);
            _ui_screen_change(&ui_Done, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Done_screen_init);
            progress = 0;
            gUIRecord.seconds =0;
            is_WaittoLogo = true;
            return;
        }
        else
        {
            lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            // linee++;
            // if (linee == 5)
            // {
            //     if (sccor)
            //     {
            //         lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x21FE00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            //     }
            //     else
            //     {
            //         lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            //     }
            //     sccor = !sccor;
            //     linee = 0;
            // }
        }
    }
    // 增加进度
    progress++;
}

void timer_callback(void *arg)
{
    update_Time++;
    if (update_Time == 600)
    {
        getNetTime();
        update_Time = 0;
    }
    // ESP_LOGI("ui.c", "seconds+= %lu ClockTime=:%d,gUIRecord.currentUI=%d", gUIRecord.seconds, ClockTime, gUIRecord.currentUI);
    if (gUIRecord.currentUI == UI_LOGO && gUIRecord.seconds >= chaneScreenTime)
    {
        _ui_screen_change(&ui_CLOCK, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_CLOCK_screen_init);
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_CLOCK;
        xSemaphoreGive(gUIRecordMutex);
        gUIRecord.seconds = 0;
        return;
    }
    else if (gUIRecord.currentUI == UI_CLOCK && gUIRecord.seconds >= chaneScreenTime)
    {
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_LOGO;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_Logo_screen_init);
        gUIRecord.seconds = 0;
        return;
    }
    else if (gUIRecord.currentUI == UI_CLOCK)
    {
        // 获取系统时间戳
        time_t now = 0;
        time(&now);
        setenv("TZ", "CST-8", 1);
        tzset();
        // 结合设置的时区，转换为tm结构体
        struct tm timeinfo = {0};
        localtime_r(&now, &timeinfo);
        // 转为字符串（方法随意，不一定要用strftime）
        char str[64];
        strftime(str, sizeof(str), "%c", &timeinfo);
        ESP_LOGI("test", "strftime %s", str);
        char weekdayName[20];
        char monthName[20];
        char dateString[64];
        strftime(weekdayName, sizeof(weekdayName), "%A", &timeinfo); // 获取星期几的英文名称
        strftime(monthName, sizeof(monthName), "%B", &timeinfo);     // 获取月份的英文名称
        snprintf(dateString, sizeof(dateString), "%s %02d, %s", weekdayName, timeinfo.tm_mday, monthName);
        ClockTime = timeinfo.tm_hour * 3600 + timeinfo.tm_min * 60 + timeinfo.tm_sec;

        uint32_t hours = ClockTime / 3600;
        uint32_t minutes = (ClockTime % 3600) / 60;
        char hourtimeString[64];
        char minutestimeString[64];
        snprintf(hourtimeString, sizeof(hourtimeString), "%02ld", (long)hours);
        snprintf(minutestimeString, sizeof(minutestimeString), "%02ld", (long)minutes);
        // 更新 lvgl label 控件的文本
        lv_label_set_text(ui_Label10, hourtimeString);
        lv_label_set_text(ui_Label12, minutestimeString);
        lv_label_set_text(ui_data, dateString);
    }
    else if (gUIRecord.currentUI == UI_INSERT_POD)
    {
        if (gUIRecord.seconds >= 40)
        {
            xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
            gUIRecord.currentUI = UI_LOGO;
            xSemaphoreGive(gUIRecordMutex);
            // 在提示界面 40秒没有操作 则跳回LOGO界面
            _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_Logo_screen_init);
        }
    }
    else if (gUIRecord.currentUI == UI_INSERT_POD && is_CloseDoor && gUIRecord.seconds > 5)
    {
        // 在提示界面 并且关门 则开始检测QR
        gUIRecord.seconds = 0; // 模拟10秒扫码成功
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_CHOSE_COFFEE;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_chose_coffee, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_chose_coffee_screen_init);
    }
    else if (gUIRecord.currentUI == UI_BREWING && is_makeCoffee)
    {
    }
    else if (gUIRecord.currentUI == UI_ERROR && gUIRecord.seconds > 5)
    {
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_LOGO;
        xSemaphoreGive(gUIRecordMutex);
        gUIRecord.seconds = 0;
        _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Logo_screen_init);
    }
    else if (gUIRecord.currentUI == UI_DONE && is_WaittoLogo)
    {
        if (gUIRecord.seconds > 5)
        {
            xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
            gUIRecord.currentUI = UI_LOGO;
            xSemaphoreGive(gUIRecordMutex);
            _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Logo_screen_init);
            gUIRecord.seconds = 0;
        }
    }
    gUIRecord.seconds++;
    // ClockTime++;
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_gif(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {

        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_INSERT_POD;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_Insert_pod, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Insert_pod_screen_init);
        gUIRecord.seconds = 0;
    }
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        // _ui_screen_change(&ui_CLOCK, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_CLOCK_screen_init);
    }
}

// 时钟界面回调
void ui_event_CLOCK(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_TOUCH_TO_START;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_Touch_to_start, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_Touch_to_start_screen_init);
        gUIRecord.seconds = 0;
    }
}

void ui_event_ButStartScanQr(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_Image1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        is_startScanQr = !is_startScanQr;
    }
}
// 等待放入胶囊并且关闭门
void ui_event_Insert_pod(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_TOUCH_TO_START;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_Touch_to_start, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_Touch_to_start_screen_init);
    }
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        is_CloseDoor = true;
    }
}
// mak ice coffeee
void ui_event_Button3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        ESP_LOGI("ui_event_Button1", "cheeck");
        gUIRecord.seconds = 0; //
        is_makeCoffee = true;
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_BREWING;
        xSemaphoreGive(gUIRecordMutex);
        progress = 0;
        _ui_screen_change(&ui_brewing, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_brewing_screen_init);
    }
}
// make hot coffe
void ui_event_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        ESP_LOGI("ui_event_Button1", "cheeck");
        gUIRecord.seconds = 0; //
        is_makeCoffee = true;
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_BREWING;
        xSemaphoreGive(gUIRecordMutex);
        progress = 0;
        _ui_screen_change(&ui_brewing, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_brewing_screen_init);
        //  xTaskCreate(arc_update_task, "ARC Update Task", 4096, NULL, 10, &arcTaskHandle);
    }
}
void ui_event_Arc1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        progress = 0;
        is_makeCoffee = false;
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_ERROR;
        xSemaphoreGive(gUIRecordMutex);
        _ui_screen_change(&ui_Error, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Error_screen_init);
    }
}
void ui_event_Done(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        // xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        // gUIRecord.currentUI = UI_LOGO;
        // xSemaphoreGive(gUIRecordMutex);
        // _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 3000, &ui_Logo_screen_init);
    }
}
void ui_event_Error(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_LOGO;
        xSemaphoreGive(gUIRecordMutex);
        gUIRecord.seconds = 0;
        _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Logo_screen_init);
    }
}

//---------------------ui_Touch_to_start function-----------------------------------------------------//
void ui_event_connection_wifi(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_ConnWifi2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Password2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_FOCUSED)
    {
        lv_keyboard_set_textarea(ui_Keyboard3, ui_Password2);
        showkey_Animation(ui_Keyboard3, 0);
    }
}
void ui_event_AreaWifiName2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // _ui_flag_modify(ui_Logo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        lv_keyboard_set_textarea(ui_Keyboard3, ui_AreaWifiName2);
        showkey_Animation(ui_Keyboard3, 0);
    }
}
void ui_event_Keyboard3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_READY)
    {
        hidkey_Animation(ui_Keyboard3, 0);
    }
}
void ui_event_butskip2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        ESP_LOGI("teest", "skip cheeks");
        _ui_flag_modify(ui_ConnWifi2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PasswordKey2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        hidkey_Animation(ui_Keyboard3, 0);
    }
}
// to chose make coffee
void ui_event_ButStartstart(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
        gUIRecord.currentUI = UI_CHOSE_COFFEE;
        xSemaphoreGive(gUIRecordMutex);
        gUIRecord.seconds = 0;
        is_startScanQr = false;
        _ui_screen_change(&ui_chose_coffee, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_chose_coffee);
    }
}
void ui_event_ButStartqr(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        if (!is_startScanQr)
        {
            is_startScanQr = true;
            _ui_flag_modify(ui_Image1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        }
        else
        {
            is_startScanQr = false;
            _ui_flag_modify(ui_Image1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
            xSemaphoreTake(gUIRecordMutex, portMAX_DELAY);
            gUIRecord.currentUI = UI_LOGO;
            xSemaphoreGive(gUIRecordMutex);
            _ui_screen_change(&ui_Logo, LV_SCR_LOAD_ANIM_FADE_ON, uiChangeTime, 0, &ui_Logo_screen_init);
            gUIRecord.seconds = 0;
        }
    }
}
void ui_event_BtnConnWIfi2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        // ConnWIfi(e);
    }
}
//---------------------CUSTOM FUN-------------------------------------------

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Logo_screen_init();
    ui_CLOCK_screen_init();
    ui_Touch_to_start_screen_init();
    ui_Insert_pod_screen_init();
    ui_Reinforce_screen_init();
    ui_chose_coffee_screen_init();
    ui_brewing_screen_init();
    ui_Done_screen_init();
    ui_Error_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    gUIRecordMutex = xSemaphoreCreateMutex();
    // 创建定时器，周期为 1 秒
    lv_disp_load_scr(ui_Logo);
    esp_timer_create_args_t timer_config = {
        .callback = timer_callback,
        .arg = NULL,
        .dispatch_method = ESP_TIMER_TASK,
        .name = "my_timer"};

    // 创建定时器
    esp_timer_handle_t timer;
    esp_timer_create(&timer_config, &timer);
    // 启动定时器，定时1秒
    esp_timer_start_periodic(timer, 1000000); // 1秒 = 1000000微秒
                                              // 创建定时器
    esp_timer_create_args_t timer_config1 = {
        .callback = timer_callback1,
        .arg = NULL,
        .dispatch_method = ESP_TIMER_TASK,
        .name = "my_timer1"};

    // 创建定时器
    esp_timer_handle_t timer1;
    esp_timer_create(&timer_config1, &timer1);
    // 启动定时器，定时1秒
    esp_timer_start_periodic(timer1, 50000); // 1秒 = 1000000微秒
                                             // 创建定时器
}
