// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"

void ui_chose_coffee_screen_init(void)
{
    ui_chose_coffee = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_chose_coffee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chose_coffee, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chose_coffee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_Image5 = lv_img_create(ui_chose_coffee);
    lv_img_set_src(ui_Image5, &ui_img_ice_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -103);
    lv_obj_set_y(ui_Image5, -27);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
  //  lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x38994C), LV_PART_MAIN | LV_STATE_DEFAULT);
   // lv_obj_set_style_img_recolor_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_chose_coffee);
    lv_img_set_src(ui_Image6, &ui_img_hotcoffee_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image6, 89);
    lv_obj_set_y(ui_Image6, -48);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_chose_coffee);
    lv_obj_set_width(ui_Button3, 118);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -107);
    lv_obj_set_y(ui_Button3, 96);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabMsgIce = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_LabMsgIce, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabMsgIce, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabMsgIce, -1);
    lv_obj_set_y(ui_LabMsgIce, -2);
    lv_obj_set_align(ui_LabMsgIce, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMsgIce, "Iced");
    lv_obj_set_style_text_font(ui_LabMsgIce, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_chose_coffee);
    lv_obj_set_width(ui_Button1, 118);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 103);
    lv_obj_set_y(ui_Button1, 98);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabMsghot = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_LabMsghot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabMsghot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabMsghot, 1);
    lv_obj_set_y(ui_LabMsghot, -2);
    lv_obj_set_align(ui_LabMsghot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMsghot, "Hot");
    lv_obj_set_style_text_font(ui_LabMsghot, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
