// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"

void ui_Error_screen_init(void)
{
    ui_Error = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Error, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Error, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Error, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrorMsgError = lv_label_create(ui_Error);
    lv_obj_set_width(ui_ErrorMsgError, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ErrorMsgError, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrorMsgError, -157);
    lv_obj_set_y(ui_ErrorMsgError, -50);
    lv_obj_set_align(ui_ErrorMsgError, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrorMsgError, "Error");
    lv_obj_set_style_text_font(ui_ErrorMsgError, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MsgErrorInfo = lv_label_create(ui_Error);
    lv_obj_set_width(ui_MsgErrorInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MsgErrorInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MsgErrorInfo, -105);
    lv_obj_set_y(ui_MsgErrorInfo, 43);
    lv_obj_set_align(ui_MsgErrorInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MsgErrorInfo, "There is no cup\nplace a cup on\nthe machine \ntocontinue");
    lv_obj_set_style_text_font(ui_MsgErrorInfo, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgErrormsg = lv_img_create(ui_Error);
    lv_img_set_src(ui_ImgErrormsg, &ui_img_error_png);
    lv_obj_set_width(ui_ImgErrormsg, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ImgErrormsg, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ImgErrormsg, 82);
    lv_obj_set_y(ui_ImgErrormsg, -4);
    lv_obj_set_align(ui_ImgErrormsg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgErrormsg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgErrormsg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Error, ui_event_Error, LV_EVENT_ALL, NULL);

}
