// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"

void ui_Insert_pod_screen_init(void)
{
    ui_Insert_pod = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Insert_pod, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Insert_pod, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Insert_pod, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Insert_pod);
   lv_img_set_src(ui_Image8, &ui_img_200_200insert_png);
    // lv_img_set_src(ui_Image8, "S:/pictures/012.png");

    // lv_img_set_src(ui_Image8, "S:/pictures/wifi.png");

    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 3);
    lv_obj_set_y(ui_Image8, -45);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabMsgInsert = lv_label_create(ui_Insert_pod);
    lv_obj_set_width(ui_LabMsgInsert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabMsgInsert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabMsgInsert, 5);
    lv_obj_set_y(ui_LabMsgInsert, 90);
    lv_obj_set_align(ui_LabMsgInsert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMsgInsert, "Open Lid to insert your pod");

    lv_obj_add_event_cb(ui_Insert_pod, ui_event_Insert_pod, LV_EVENT_ALL, NULL);

}
