// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"

void ui_Logo_screen_init(void)
{
    ui_Logo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_Logo, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Logo);
    lv_obj_set_style_bg_color(ui_Logo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Logo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_Logo, "S:/pictures/012.png", LV_PART_MAIN | LV_STATE_DEFAULT);
    // ui_gif = lv_obj_create(ui_Logo);
    // lv_obj_set_width(ui_gif, 544);
    // lv_obj_set_height(ui_gif, 506);
    // lv_obj_set_align(ui_gif, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_gif, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // lv_obj_set_style_radius(ui_gif, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_gif, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_gif, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gifdata = lv_gif_create(ui_Logo);

    uint32_t random_number = esp_random() % 3;
    ESP_LOGI("TAG", "随机数%lu ", random_number);
    char result[64];
    strcpy(result, "S:gif/");
    // 将随机数转换为字符串并连接到结果数组
    snprintf(result + strlen(result), sizeof(result) - strlen(result), "%lu", random_number);
    strcat(result, ".gif");
    ESP_LOGI("TAG", "合并后的字符串：%s", result);
    lv_gif_set_src(ui_gifdata, result);

    // lv_gif_set_src(ui_gifdata,"S:/sdcard/pictures/gif/orange_raw.bin");
    //   lv_gif_set_src(ui_gifdata,"S:/sdcard/pictures/gif/xiaoji_yellow.bin");
    // lv_gif_set_src(ui_gifdata,"S:/sdcard/pictures/gif/cat.gif");
    lv_obj_set_width(ui_gifdata, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_gifdata, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_gifdata, LV_ALIGN_CENTER);
    lv_obj_align(ui_gifdata, LV_ALIGN_CENTER, 0, 0);

    //  ui_Image1 = lv_gif_create(ui_Screen1);

    //     lv_gif_set_src(ui_Image1, "S:/gif/&xiaoji_yellow.bin");
    //     lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 1
    //     lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 1
    //     lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    //     lv_obj_align(ui_Image1, LV_ALIGN_CENTER, 0, 0);

    lv_obj_add_event_cb(ui_Logo, ui_event_gif, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gifdata, ui_event_gif, LV_EVENT_ALL, NULL);
}
