// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"

void ui_Reinforce_screen_init(void)
{
    ui_Reinforce = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Reinforce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
