// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 咖啡机3.6寸

#include "ui.h"

void ui_Touch_to_start_screen_init(void)
{

    ui_Touch_to_start = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Touch_to_start, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Touch_to_start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Touch_to_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Touch_to_start);
    lv_obj_set_width(ui_Panel4, 150);
    lv_obj_set_height(ui_Panel4, 150);
    lv_obj_set_x(ui_Panel4, -4);
    lv_obj_set_y(ui_Panel4, -8);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButStartstart = lv_btn_create(ui_Touch_to_start);
    lv_obj_set_width(ui_ButStartstart, 153);
    lv_obj_set_height(ui_ButStartstart, 52);
    lv_obj_set_x(ui_ButStartstart, -184);
    lv_obj_set_y(ui_ButStartstart, -29);
    lv_obj_set_align(ui_ButStartstart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButStartstart, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButStartstart, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_ButStartstart, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButStartstart, lv_color_hex(0x03C3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButStartstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButStartstart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButStartstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButStartstart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ButStartstart);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Start");

    ui_Image1 = lv_img_create(ui_Touch_to_start);
    // lv_img_set_src(ui_Image1, &ui_img_256895308);
    lv_obj_set_width(ui_Image1, 320);
    lv_obj_set_height(ui_Image1, 240);
    lv_obj_set_x(ui_Image1, 67);
    lv_obj_set_y(ui_Image1, 2);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                                     LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, -110);
    lv_obj_set_y(ui_Label4, -140);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "QR TEXT:");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButStartqr = lv_btn_create(ui_Touch_to_start);
    lv_obj_set_width(ui_ButStartqr, 153);
    lv_obj_set_height(ui_ButStartqr, 52);
    lv_obj_set_x(ui_ButStartqr, -185);
    lv_obj_set_y(ui_ButStartqr, 43);
    lv_obj_set_align(ui_ButStartqr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButStartqr, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ButStartqr, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_ButStartqr, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButStartqr, lv_color_hex(0xF9FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButStartqr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButStartqr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButStartqr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButStartqr, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ButStartqr);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SCAN_QR");

    ui_LabMsgqr = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_LabMsgqr, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabMsgqr, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabMsgqr, -11);
    lv_obj_set_y(ui_LabMsgqr, -140);
    lv_obj_set_align(ui_LabMsgqr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMsgqr, "NULL");
    lv_obj_set_style_text_color(ui_LabMsgqr, lv_color_hex(0xE80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabMsgqr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labMsgWIfiMode = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labMsgWIfiMode, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labMsgWIfiMode, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labMsgWIfiMode, -106);
    lv_obj_set_y(ui_labMsgWIfiMode, -209);
    lv_obj_set_align(ui_labMsgWIfiMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMsgWIfiMode, "WIFI MODE :");
    lv_obj_set_style_text_font(ui_labMsgWIfiMode, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labWifiMode = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labWifiMode, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labWifiMode, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labWifiMode, -60);
    lv_obj_set_y(ui_labWifiMode, -208);
    lv_obj_set_align(ui_labWifiMode, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_labWifiMode, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labMsgWIfIP = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labMsgWIfIP, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labMsgWIfIP, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labMsgWIfIP, -100);
    lv_obj_set_y(ui_labMsgWIfIP, -161);
    lv_obj_set_align(ui_labMsgWIfIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMsgWIfIP, "WIFI IP:");
    lv_obj_set_style_text_font(ui_labMsgWIfIP, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labWifiip = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labWifiip, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labWifiip, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labWifiip, -44);
    lv_obj_set_y(ui_labWifiip, -161);
    lv_obj_set_align(ui_labWifiip, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_labWifiip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labMsgWIfiID = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labMsgWIfiID, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labMsgWIfiID, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labMsgWIfiID, -99);
    lv_obj_set_y(ui_labMsgWIfiID, -192);
    lv_obj_set_align(ui_labMsgWIfiID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMsgWIfiID, "WIFI ID :");
    lv_obj_set_style_text_font(ui_labMsgWIfiID, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labWIfiid = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labWIfiid, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labWIfiid, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labWIfiid, -49);
    lv_obj_set_y(ui_labWIfiid, -193);
    lv_obj_set_align(ui_labWIfiid, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_labWIfiid, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labMsgWIfiPD = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labMsgWIfiPD, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labMsgWIfiPD, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labMsgWIfiPD, -99);
    lv_obj_set_y(ui_labMsgWIfiPD, -177);
    lv_obj_set_align(ui_labMsgWIfiPD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labMsgWIfiPD, "WIFI PD :");
    lv_obj_set_style_text_font(ui_labMsgWIfiPD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labWifipd = lv_label_create(ui_Touch_to_start);
    lv_obj_set_width(ui_labWifipd, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labWifipd, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_labWifipd, -46);
    lv_obj_set_y(ui_labWifipd, -176);
    lv_obj_set_align(ui_labWifipd, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_labWifipd, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connection_wifi = lv_btn_create(ui_Touch_to_start);
    lv_obj_set_width(ui_connection_wifi, 106);
    lv_obj_set_height(ui_connection_wifi, 36);
    lv_obj_set_x(ui_connection_wifi, 53);
    lv_obj_set_y(ui_connection_wifi, -185);
    lv_obj_set_align(ui_connection_wifi, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_connection_wifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_connection_wifi, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_connection_wifi, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connection_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_connection_wifi);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "check to \nconn wfi");

    ui_ConnWifi2 = lv_obj_create(ui_Touch_to_start);
    lv_obj_set_width(ui_ConnWifi2, 544);
    lv_obj_set_height(ui_ConnWifi2, 506);
    lv_obj_set_align(ui_ConnWifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnWifi2, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_ConnWifi2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_ConnWifi2, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnWifi2, 240, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ConnWifi2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label16, -4);
    lv_obj_set_y(ui_Label16, -170);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Connection WiFi");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xACABA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiList2 = lv_obj_create(ui_ConnWifi2);
    lv_obj_set_width(ui_WifiList2, 307);
    lv_obj_set_height(ui_WifiList2, 136);
    lv_obj_set_x(ui_WifiList2, 8);
    lv_obj_set_y(ui_WifiList2, -48);
    lv_obj_set_align(ui_WifiList2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiList2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_PasswordKey2 = lv_obj_create(ui_ConnWifi2);
    lv_obj_set_width(ui_PasswordKey2, 410);
    lv_obj_set_height(ui_PasswordKey2, 307);
    lv_obj_set_x(ui_PasswordKey2, 3);
    lv_obj_set_y(ui_PasswordKey2, 41);
    lv_obj_set_align(ui_PasswordKey2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PasswordKey2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Password2 = lv_textarea_create(ui_PasswordKey2);
    lv_obj_set_width(ui_Password2, 153);
    lv_obj_set_height(ui_Password2, LV_SIZE_CONTENT); /// 33
    lv_obj_set_x(ui_Password2, 21);
    lv_obj_set_y(ui_Password2, -44);
    lv_obj_set_align(ui_Password2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Password2, "Input Password");
    lv_textarea_set_one_line(ui_Password2, true);

    ui_BtnConnWIfi2 = lv_btn_create(ui_PasswordKey2);
    lv_obj_set_width(ui_BtnConnWIfi2, 104);
    lv_obj_set_height(ui_BtnConnWIfi2, 35);
    lv_obj_set_x(ui_BtnConnWIfi2, -12);
    lv_obj_set_y(ui_BtnConnWIfi2, 19);
    lv_obj_set_align(ui_BtnConnWIfi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConnWIfi2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_BtnConnWIfi2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Label13 = lv_label_create(ui_BtnConnWIfi2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label13, -2);
    lv_obj_set_y(ui_Label13, 1);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Connnection");

    ui_WIFI_Name2 = lv_label_create(ui_PasswordKey2);
    lv_obj_set_width(ui_WIFI_Name2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_WIFI_Name2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_WIFI_Name2, -106);
    lv_obj_set_y(ui_WIFI_Name2, -100);
    lv_obj_set_align(ui_WIFI_Name2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WIFI_Name2, "WifiName");

    ui_AreaWifiName2 = lv_textarea_create(ui_PasswordKey2);
    lv_obj_set_width(ui_AreaWifiName2, 150);
    lv_obj_set_height(ui_AreaWifiName2, LV_SIZE_CONTENT); /// 33
    lv_obj_set_x(ui_AreaWifiName2, 21);
    lv_obj_set_y(ui_AreaWifiName2, -99);
    lv_obj_set_align(ui_AreaWifiName2, LV_ALIGN_CENTER);

    lv_textarea_set_one_line(ui_AreaWifiName2, true);

    ui_Label14 = lv_label_create(ui_PasswordKey2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label14, -107);
    lv_obj_set_y(ui_Label14, -43);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Password");

    ui_Keyboard3 = lv_keyboard_create(ui_ConnWifi2);
    lv_keyboard_set_mode(ui_Keyboard3, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_width(ui_Keyboard3, 410);
    lv_obj_set_height(ui_Keyboard3, 183);
    lv_obj_set_x(ui_Keyboard3, 0);
    lv_obj_set_y(ui_Keyboard3, 350);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Keyboard3, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard3, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_butskip2 = lv_btn_create(ui_ConnWifi2);
    lv_obj_set_width(ui_butskip2, 82);
    lv_obj_set_height(ui_butskip2, 31);
    lv_obj_set_x(ui_butskip2, 96);
    lv_obj_set_y(ui_butskip2, 117);
    lv_obj_set_align(ui_butskip2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_butskip2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_butskip2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_labskip2 = lv_label_create(ui_butskip2);
    lv_obj_set_width(ui_labskip2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_labskip2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_labskip2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labskip2, "Skip");

    char WIFI_Name[50] = {0};
    char WIFI_PassWord[50] = {0}; /*读取保存的WIFI信息*/
    char WIFI_IP[50] = {0};       /*读取保存的WIFI信息*/
    if (NvsReadDataFromFlash("WIFI Config", WIFI_Name, WIFI_PassWord) == 0x00)
    {
        printf("WIFI SSID     :%s\r\n", WIFI_Name);
        printf("WIFI PASSWORD :%s\r\n", WIFI_PassWord);
        printf("WIFI Station 模式\r\n");
        lv_label_set_text(ui_labWifiMode, "STA");
        lv_label_set_text(ui_labWIfiid, WIFI_Name);
        lv_label_set_text(ui_labWifipd, WIFI_PassWord);
        lv_label_set_text(ui_labWifiip, "WIFI_IP");
        lv_textarea_set_placeholder_text(ui_AreaWifiName2, WIFI_Name);
    }
    else
    {
        lv_label_set_text(ui_labWifiMode, "AP");
        lv_label_set_text(ui_labWIfiid, "CONNECTION");
        lv_label_set_text(ui_labWifipd, "12345678");
        lv_label_set_text(ui_labWifiip, "192.168.4.1");
        lv_textarea_set_placeholder_text(ui_AreaWifiName2, "Placeholder...");
    }

    lv_obj_add_event_cb(ui_ButStartstart, ui_event_ButStartstart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButStartqr, ui_event_ButStartqr, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnConnWIfi2, ui_event_BtnConnWIfi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connection_wifi, ui_event_connection_wifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Password2, ui_event_Password2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AreaWifiName2, ui_event_AreaWifiName2, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Keyboard3, ui_event_Keyboard3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordKey2, ui_event_PasswordKey2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_butskip2, ui_event_butskip2, LV_EVENT_ALL, NULL);
}
